const divisionalRankings = {
    champsByDivision: [
        {   
            type:"div",
            division: "Heavyweight",
            name: "Tyson Fury",
            record: "30-0-1",
            kos: 21,
            alias: "The Gypsy King",
            nationality: "United Kingdom", 
            stance: "orthodox",
            height: "6'9",
            reach: 85,
        },
        {   
            type:"div",
            division: "Cruiserweight",
            name: "Mairis Briedis",
            record: "27-1-0",
            kos: 21,
            alias: "none",
            nationality: "Latvia",
            stance: "orthodox",
            height: "6'1",
            reach: 75,
        },
        {
            type:"div",
            division: "Light Heavyweight",
            name: "Sergey Kovalev",
            record: "34-4-0",
            kos: 29,
            alias: "Krusher",
            nationality: "Russia", 
            stance: "orthodox",
            height: "6'0",
            reach: 72.5,
        },
        {
            type:"div",
            division: "Super Middleweight",
            name: "Callum Smith",
            record: "27-0-0",
            kos: 19,
            alias: "Mundo",
            nationality: "United Kingdom", 
            stance: "orthodox",
            height: "6'3",
            reach: 78,
        },
        {
            type:"div",
            division: "Middleweight",
            name: "Saul Alvarez",
            record: "53-1-0",
            kos: 36,
            alias: "Canelo",
            nationality: "Mexico",
            division: "Middleweight", 
            stance: "orthodox",
            height: "5'8",
            reach: 70.5,
        },
        {
            type:"div",
            division: "Super Welterweight",
            name: "Jermell Charlo",
            record: "34-1-0",
            kos: 18,
            alias: "Iron Man",
            nationality: "USA", 
            stance: "orthodox",
            height: "5'11",
            reach: 73,
        },
        {
            type:"div",
            division: "Weltherweight",
            name: "Errol Spence Jr",
            record: "26-0-0",
            kos: 21,
            alias: "The Truth",
            nationality: "USA",
            division: "Welterweight", 
            stance: "southpaw",
            height: "5'9 1/2",
            reach: 72,
        },
        {
            type:"div",
            division: "Super Lightweight",
            name: "Josh Taylor",
            record: "17-0-0",
            kos: 13,
            alias: "The Tartan Tornado",
            nationality: "United Kingdom",
            stance: "southpaw",
            height: "5'10",
            reach: 69.5,
        },
        {
            type:"div",
            division: "Lightweight",
            name: "Vasyl Lomachenko",
            record: "14-1-0",
            kos: 10,
            alias: "The Matrix",
            nationality: "Ukraine", 
            stance: "southpaw",
            height: "5'7",
            reach: 65.5,
        },
        {
            type:"div",
            division: "Super Featherweight",
            name: "Miguel Berchelt",
            record: "37-1-0",
            kos: 33,
            alias: "El Alacran",
            nationality: "Mexico", 
            stance: "orthodox",
            height: "5'7",
            reach: 71.5,
        },
    ]
}

module.exports = divisionalRankings;