const p4pBoxingRankings = {
    p4pFighters:[
        {   
            type:"p4p",
            name: "Saul Alvarez",
            record: "53-1-0",
            kos: 36,
            alias: "Canelo",
            nationality: "Mexico",
            debut: "10-29-2005",
            division: "Middleweight", 
            stance: "orthodox",
            height: "5'8",
            reach: 70.5,
        },
        {
            type:"p4p",
            name: "Tyson Luke Fury",
            record: "30-0-1",
            kos: 21,
            alias: "The Gypsy King",
            nationality: "United Kingdom",
            debut: "12-06-2008",
            division: "Heavyweight", 
            stance: "orthodox",
            height: "6'9",
            reach: 85,
        },
        {
            type:"p4p",
            name: "Errol Spence Jr",
            record: "26-0-0",
            kos: 21,
            alias: "The Truth",
            nationality: "USA",
            debut: "11-09-2012",
            division: "Welterweight", 
            stance: "southpaw",
            height: "5'9 1/2",
            reach: 72,
        },
        {
            type:"p4p",
            name: "Gennady Golovkin",
            record: "40-1-1",
            kos: 35,
            alias: "GGG",
            nationality: "Kazakhstan",
            debut: "05-06-2006",
            division: "Middleweight", 
            stance: "orthodox",
            height: "5'10 1/2",
            reach: 70,
         },
         {
            type:"p4p",
            name: "Deontay Wilder",
            record: "42-1-1",
            kos: 41,
            alias: "The Bronze Bomber",
            nationality: "USA",
            debut: "11-15-2008",
            division: "HeavyWeight", 
            stance: "orthodox",
            height: "6'7",
            reach: 83,
        },
        {
            type:"p4p",
            name: "Terrence Crawford",
            record: "36-0-0",
            kos: 27,
            alias: "Bud",
            nationality: "USA",
            debut: "03-14-2008",
            division: "Welterweight", 
            stance: "southpaw",
            height: "5'8",
            reach: 74,
        },
        {
            type:"p4p",
            name: "Anthony Joshua",
            record: "23-1-0",
            kos: 21,
            alias: "AJ",
            nationality: "United Kingdom",
            debut: "10-05-2013",
            division: "Heavyweight", 
            stance: "orthodox",
            height: "6'6",
            reach: 82,
        },
        {
            type:"p4p",
            name: "Vasyl Lomachenko",
            record: "14-1-0",
            kos: 10,
            alias: "The Matrix",
            nationality: "Ukraine",
            debut: "10-12-2013",
            division: "Lightweight", 
            stance: "southpaw",
            height: "5'7",
            reach: 65.5,
        },
        {
            type:"p4p",
            name: "Manny Pacquiao",
            record: "62-7-2",
            kos: 39,
            alias: "Pacman",
            nationality: "Phillippines",
            debut: "01-22-1995",
            division: "Welterweight", 
            stance: "southpaw",
            height: "5'5 1/2",
            reach: 67,
        },
        {
            type:"p4p",
            name: "Alexander Povetkin",
            record: "36-2-1",
            kos: 25,
            alias: "Sasha",
            nationality: "Russia",
            debut: "06-11-2005",
            division: "Heavyweight", 
            stance: "orthodox",
            height: "6'2",
            reach: 75,
        },

    ]

}



    
  module.exports = p4pBoxingRankings;