const ufcDivisionalRankings = {
    ufcDivisions: [
        {
            type: "ufcChamps",
            division: "Heavyweight",
            name: "Stipe Miocic",
            record: "20-3-0",
            kos: 15,
            submissions: 0,
            nationality: "USA", 
            stance: "Orthodox",
            height: "6'4",
            reach: 80,
        },
        {
            type: "ufcChamps" ,
            division: "Light Heavyweight",
            name: "Jan Blachowicz",
            record: "27-8-0",
            kos: 8,
            submissions: 9,
            nationality: "Poland", 
            stance: "Orthodox",
            height: "6'2",
            reach: 78,
        },
        {
            type: "ufcChamps",
            division: "Middleweight",
            name: "Isreal Adesanya",
            record: "20-0-0",
            kos: 15,
            submissions: 0,
            nationality: "Nigeria", 
            stance: "Orthodox",
            height: "6'4",
            reach: 80,
        },
        {
            type: "ufcChamps",
            division: "Welterweight",
            name: "Kamaru Usman",
            record: "17-1-0",
            kos: 7,
            submissions: 1,
            nationality: "Nigeria", 
            stance: "Orthodox",
            height: "6,0",
            reach: 76,
        },
        {
            type: "ufcChamps",
            division: "Lightweight",
            name: "Khabib Nurmagomedov",
            record: "28-0-0",
            kos: 8,
            submissions: 10,
            nationality: "Russia", 
            stance: "Orthodox",
            height: "5'10",
            reach: 70,
        },
        {
            type: "ufcChamps",
            division: "Featherweight",
            name: "Alexander Volkanovski",
            record: "22-1-0",
            kos: 11,
            submissions: 3,
            nationality: "Australia", 
            stance: "Orthodox",
            height: "5'6",
            reach: 71.5,
        },
        {
            type: "ufcChamps",
            division: "Bantamweight",
            name: "Petr Yan",
            record: "15-1-0",
            kos: 7,
            submissions: 1,
            nationality: "Russia", 
            stance: "Orthodox",
            height: "5'7 1/2",
            reach: 67,
        },
        {
            type: "ufcChamps",
            division: "Flyweight",
            name: "Deiveson Figueiredo",
            record: "20-1-0",
            kos: 9,
            submissions: 7,
            nationality: "Brazil", 
            stance: "Orthodox",
            height: "5'5",
            reach: 68,
        },
        {
            type: "ufcChamps",
            division: "Womens Featherweight",
            name: "Amanda Nunes",
            record: "20-4-0",
            kos: 13,
            submissions: 3,
            nationality: "Brazil", 
            stance: "Orthodox",
            height: "5'8",
            reach: 69,
        },
        {
            type: "ufcChamps",
            division: "Womens Bantamweight",
            name: "Amanda Nunes",
            record: "20-4-0",
            kos: 13,
            submissions: 3,
            nationality: "Brazil", 
            stance: "Orthodox",
            height: "5'8",
            reach: 69,
        }
    ]
}

module.exports = ufcDivisionalRankings;
                 