const ufcP4pRankings = {
    ufcP4pfighters: [
        {
            type: "ufcP4p",
            division: "Light Heavyweight",
            name: "jon Jones",
            record: "26-0-2",
            kos: 10,
            submissions: 6,
            nationality: "USA", 
            stance: "Orthodox",
            height: "6'4",
            reach: 84.5,
        },
        {
            type: "ufcP4p" ,
            division: "Lightweight",
            name: "Khabib Nurmagomedov",
            record: "28-0-0",
            kos: 8,
            submissions: 10,
            nationality: "Russia", 
            stance: "Orthodox",
            height: "5'10",
            reach: 70,
        },
        {
            type: "ufcP4p",
            division: "Middleweight",
            name: "Isreal Adesanya",
            record: "20-0-0",
            kos: 15,
            submissions: 0,
            nationality: "Nigeria", 
            stance: "Orthodox",
            height: "6'4",
            reach: 80,
        },
        {
            type: "ufcP4p",
            division: "Heavyweight",
            name: "Stipe Miocic",
            record: "20-3-0",
            kos: 15,
            submissions: 0,
            nationality: "USA", 
            stance: "Orthodox",
            height: "6'4",
            reach: 80,
        },
        {
            type: "ufcP4p",
            division: "Welterweight",
            name: "Kamaru Usman",
            record: "17-1-0",
            kos: 7,
            submissions: 1,
            nationality: "Nigeria", 
            stance: "Orthodox",
            height: "6,0",
            reach: 76,
        },
        {
            type: "ufcP4p",
            division: "Featherweight",
            name: "Alexander Volkanovski",
            record: "22-1-0",
            kos: 11,
            submissions: 3,
            nationality: "Australia", 
            stance: "Orthodox",
            height: "5'6",
            reach: 71.5,
        },
        {
            type: "ufcP4p",
            division: "Lightweight",
            name: "Justin Gaethje",
            record: "22-2-0",
            kos: 19,
            submissions: 1,
            nationality: "USA", 
            stance: "Orthodox",
            height: "5'11",
            reach: 70,
        },
        {
            type: "ufcP4p",
            division: "Lightweight",
            name: "Dustin Poirier",
            record: "26-6-1",
            kos: 12,
            submissions: 7,
            nationality: "USA", 
            stance: "Southpaw",
            height: "5'9",
            reach: 72,
        },
        {
            type: "ufcP4p",
            division: "Featherweight",
            name: "Max Holloway",
            record: "21-6-0",
            kos: 10,
            submissions: 2,
            nationality: "USA", 
            stance: "Orthodox",
            height: "5'11",
            reach: 69,
        },
        {
            type: "ufcP4p",
            division: "Bantamweight",
            name: "Petr Yan",
            record: "15-1-0",
            kos: 7,
            submissions: 1,
            nationality: "Russia", 
            stance: "Orthodox",
            height: "5'7 1/2",
            reach: 67,
        },
    ]
}

module.exports = ufcP4pRankings;