const UfcRankings = {
    ufcRankings: [
        {
            type: ,
            division: ,
            name: ,
            record: ,
            kos: 21,
            alias: ,
            nationality: , 
            stance: ,
            height: ,
            reach: ,
        },
        {
            type: ,
            division: ,
            name: ,
            record: ,
            kos: 21,
            alias: ,
            nationality: , 
            stance: ,
            height: ,
            reach: ,
        },
        {
            type: ,
            division: ,
            name: ,
            record: ,
            kos: 21,
            alias: ,
            nationality: , 
            stance: ,
            height: ,
            reach: ,
        },
        {
            type: ,
            division: ,
            name: ,
            record: ,
            kos: 21,
            alias: ,
            nationality: , 
            stance: ,
            height: ,
            reach: ,
        },
        {
            type: ,
            division: ,
            name: ,
            record: ,
            kos: 21,
            alias: ,
            nationality: , 
            stance: ,
            height: ,
            reach: ,
        },
        {
            type: ,
            division: ,
            name: ,
            record: ,
            kos: 21,
            alias: ,
            nationality: , 
            stance: ,
            height: ,
            reach: ,
        },
        {
            type: ,
            division: ,
            name: ,
            record: ,
            kos: 21,
            alias: ,
            nationality: , 
            stance: ,
            height: ,
            reach: ,
        },
        {
            type: ,
            division: ,
            name: ,
            record: ,
            kos: 21,
            alias: ,
            nationality: , 
            stance: ,
            height: ,
            reach: ,
        },
        {
            type: ,
            division: ,
            name: ,
            record: ,
            kos: 21,
            alias: ,
            nationality: , 
            stance: ,
            height: ,
            reach: ,
        },
        {
            type: ,
            division: ,
            name: ,
            record: ,
            kos: 21,
            alias: ,
            nationality: , 
            stance: ,
            height: ,
            reach: ,
        },
    ]
}